name: Daily Greeting

on:
  schedule:
    - cron: '0 0 * * *'  # 6 PM CST
  workflow_dispatch:

jobs:
  interact:
    runs-on: ubuntu-latest
    environment: prod   # ✅ must match Terraform's environment name

    steps:
      - name: Say hi
        run: echo "hi ${{ vars.USER_NAME }}"

      - name: Ask how are you
        run: echo "how are you ${{ vars.USER_NAME }}?"

      - name: Say bye
        run: echo "bye ${{ vars.USER_NAME }}"


name: Daily Echo

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  interact:
    runs-on: ubuntu-latest
    env:
      USER_NAME: "F"
    steps:
      - name: Say hi
        run: echo "hi $USER_NAME"

      - name: Ask how are you
        run: echo "how are you $USER_NAME?"

      - name: Say bye
        run: echo "bye $USER_NAME"

  greet_t:
    runs-on: ubuntu-latest
    steps:
      - name: Say hi to T
        run: echo "Hi T"
