name: Daily Greeting

on:
  schedule:
    - cron: '0 0 * * *'  # 6 PM CST
  workflow_dispatch:

jobs:
  interact:
    runs-on: ubuntu-latest
    environment: prod   # ✅ must match Terraform's environment name

    steps:
      - name: Say hi
        run: echo "hi ${{ vars.USER_NAME }}"

      - name: Ask how are you
        run: echo "how are you ${{ vars.USER_NAME }}?"

      - name: Say bye
        run: echo "bye ${{ vars.USER_NAME }}"