name: Daily Greeting

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at 6 PM CST
  workflow_dispatch:

env:  # ✅ Global GitHub environment variable
  USER_NAME: F

jobs:
  interact:
    runs-on: ubuntu-latest

    steps:
      - name: Say hi
        run: echo "hi $USER_NAME"

      - name: Ask how are you
        run: echo "how are you $USER_NAME?"

      - name: Say bye
        run: echo "bye $USER_NAME"
